package com.vintagevinyl.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "records") // Maps the class to a database table named 'records'
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Record {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    // The primary key for this entity, auto-generated by the database
    private Long id;

    @Column(nullable = false) // Ensures the 'title' column cannot be null in the database
    private String title;

    @Column(nullable = false) // Ensures the 'artist' column cannot be null in the database
    private String artist;

    @Column(name = "album")
    private String album;

    @Column(name = "release_date")
    private LocalDate releaseDate;

    @Column(name = "cover_image_url")
    private String coverImageUrl;

    private String genre;

    private BigDecimal price;

    @OneToMany(mappedBy = "record", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<CartItem> cartItems = new ArrayList<>();

    public void removeCartItem(CartItem item) {
        cartItems.remove(item);
        item.setRecord(null);
    }
}
